name: Check for update and release

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  call-workflow:
    uses: linuxserver-labs/docker-actions/.github/workflows/check-and-release.yml@v5
    with:
      repo_owner: ${{ github.repository_owner }}
      app_name: "invoiceninja"
      release_type: "script"
    secrets:
      repo_release_token: ${{ secrets.repo_release_token }}
