#!/usr/bin/with-contenv bash

cd /app/invoiceninja

# copy config
[[ ! -e /config/user.ini ]] && \
	cp /defaults/user.ini /config/user.ini
cp /config/user.ini /etc/php7/conf.d/99-user.ini

# handle storage directory
[[ ! -e "/config/storage" ]] && \
	mv /app/invoiceninja/storage /config/

rm -rf /app/invoiceninja/storage
ln -s /config/storage /app/invoiceninja/storage
mkdir -p /config/storage/app/public

# check for .env and copy default if needed
if [ ! -f "/config/.env" ]; then
	cp /app/invoiceninja/.env.example /config/.env
fi

ln -sf /config/.env /app/invoiceninja/.env
php artisan key:generate --quiet

php artisan storage:link
php artisan migrate --force
php artisan optimize

# install crontab
crontab -u abc /defaults/crontabs/abc

# permissions
find . -maxdepth 1 ! -name '.' ! -name '..' ! -name 'vendor' -exec chown -R abc:abc {} \;
chown -R abc:abc \
	/config
chown abc:abc \
	/app \
	/app/invoiceninja
