#!/usr/bin/with-contenv bash

if [ -d /app-tmp ]; then
    echo "New container detected. Setting up app folder and fixing permissions."
    mv /app-tmp /app
    chown -R abc:abc /app
fi

cd /app/invoiceninja

# copy config
[[ ! -e /config/user.ini ]] && \
    cp /defaults/user.ini /config/user.ini
cp /config/user.ini /etc/php7/conf.d/99-user.ini

# handle storage directory
[[ ! -e "/config/storage" ]] && \
    mv /app/invoiceninja/storage /config/

rm -rf /app/invoiceninja/storage
ln -s /config/storage /app/invoiceninja/storage
mkdir -p /config/storage/app/public

# check for .env and copy default if needed
if [ ! -f "/config/.env" ]; then
    cp /app/invoiceninja/.env.example /config/.env
fi

ln -sf /config/.env /app/invoiceninja/.env
php artisan key:generate --quiet

php artisan storage:link
php artisan migrate --force
php artisan optimize

# install crontab
crontab -u abc /defaults/crontabs/abc

chown -R abc:abc /config
